controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_conference:
    path: /conference
    controller: App\Controller\ConferenceController::index

app_create:
    path: /api/register
    controller: App\Infrastructure\Controller\UserController::createUser
    methods: [POST]

api_login_check:
    path: /api/login_check