controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_conference:
    path: /conference
    controller: App\Controller\ConferenceController::index
